---
apiVersion: v1
kind: Service
metadata:
  name: ha-proxy
  namespace: ha-proxy
spec:
  type: LoadBalancer
  ports:
    - port: 443  
      protocol: TCP
      targetPort: 443
  selector:
    app: ha-proxy