---
apiVersion: v1
kind: Namespace
metadata:
  name: landing-page
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: landing-page
  namespace: landing-page
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  namespace: landing-page
spec:
  selector:
    matchLabels:
      app: landing-page
  replicas: 1
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      serviceAccountName: landing-page
      containers:
        - name: landing-page
          image: dylanmunyard/pi-landing-page:0.3
          imagePullPolicy: Always
      nodeSelector:
        pi_level: level2
        