---
apiVersion: v1
kind: Service
metadata:
  name: landing-page
  namespace: landing-page
spec:
  type: LoadBalancer
  ports:
    - port: 8097
      protocol: TCP
      targetPort: 80
  selector:
    app: landing-page