---
apiVersion: v1
kind: Namespace
metadata:
  name: plex-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plex-server
  namespace: plex-server
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plx-library
  namespace: plex-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plx-library
  namespace: plex-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plx-media
  namespace: plex-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plx-media-v2
  namespace: plex-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4000Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-server
  namespace: plex-server
spec:
  selector:
    matchLabels:
      app: plex-server
  replicas: 1
  template:
    metadata:
      labels:
        app: plex-server
    spec:
      serviceAccountName: plex-server
      containers:
        - name: plex-server
          image: linuxserver/plex:1.26.0
          imagePullPolicy: Always
          volumeMounts:
            - name: plx-library
              mountPath: "/config"
            - name: plx-media
              mountPath: "/data/media"
            - name: plx-media-v2
              mountPath: "/data/media_v2"
            - name: banners-cert
              mountPath: "/certs"
          env:
            - name: VERSION
              value: "docker"
      volumes:
        - name: plx-library
          persistentVolumeClaim:
            claimName: plx-library
        - name: plx-media
          persistentVolumeClaim:
            claimName: plx-media
        - name: plx-media-v2
          persistentVolumeClaim:
            claimName: plx-media-v2
        - name: banners-cert
          configMap:
            name: banners-cert
        
