---
apiVersion: v1
kind: Service
metadata:
  name: plex-server
  namespace: plex-server
spec:
  type: LoadBalancer
  ports:
    - port: 32400
      protocol: TCP
      targetPort: 32400
  selector:
    app: plex-server
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: plex-ingress
  namespace: plex-server
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`plex.bansion`)
    kind: Rule
    services:
    - name: plex-server
      port: 32400
      kind: Service
      namespace: plex-server