---
apiVersion: v1
kind: Service
metadata:
  name: plex-server
  namespace: plex-server
spec:
  type: LoadBalancer
  ports:
    - port: 32400
      protocol: TCP
      targetPort: 32400
  selector:
    app: plex-server