---
apiVersion: v1
kind: Namespace
metadata:
  name: emby-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emby-server
  namespace: emby-server
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emby-config
  namespace: emby-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emby-media
  namespace: emby-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby-server
  namespace: emby-server
spec:
  selector:
    matchLabels:
      app: emby-server
  replicas: 1
  template:
    metadata:
      labels:
        app: emby-server
    spec:
      serviceAccountName: emby-server
      containers:
        - name: emby-server
          image: ghcr.io/linuxserver/emby
          imagePullPolicy: Always
          volumeMounts:
            - name: emby-config
              mountPath: "/config"
            - name: emby-media
              mountPath: "/data/media"
          env:
            - name: TZ
              value: "Australia/Brisbane"
      volumes:
        - name: emby-config
          persistentVolumeClaim:
            claimName: emby-config
        - name: emby-media
          persistentVolumeClaim:
            claimName: emby-media
      nodeSelector:
        pi.attached.storage/exists: "true"
        
