---
apiVersion: v1
kind: Namespace
metadata:
  name: emby-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emby-server
  namespace: emby-server
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emby-library
  namespace: emby-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emby-tvshows
  namespace: emby-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emby-movies
  namespace: emby-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby-server
  namespace: emby-server
spec:
  selector:
    matchLabels:
      app: emby-server
  replicas: 1
  template:
    metadata:
      labels:
        app: emby-server
    spec:
      serviceAccountName: emby-server
      containers:
        - name: emby-server
          image: ghcr.io/linuxserver/emby
          imagePullPolicy: Always
          volumeMounts:
            - name: emby-library
              mountPath: "/config"
            - name: emby-tvshows
              mountPath: "/data/tvshows"
            - name: emby-movies
              mountPath: "/data/movies"
          env:
            - name: TZ
              value: "Australia/Brisbane"
      volumes:
        - name: emby-library
          persistentVolumeClaim:
            claimName: emby-library
        - name: emby-tvshows
          persistentVolumeClaim:
            claimName: emby-tvshows
        - name: emby-movies
          persistentVolumeClaim:
            claimName: emby-movies
      nodeSelector:
        pi.attached.storage/exists: "true"
        