---
apiVersion: v1
kind: Service
metadata:
  name: emby-server
  namespace: emby-server
spec:
  type: LoadBalancer
  ports:
    - port: 8096
      protocol: TCP
      targetPort: 8096
  selector:
    app: emby-server