---
apiVersion: v1
kind: Namespace
metadata:
  name: pi-hole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pi-hole
  namespace: pi-hole
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etc-pihole
  namespace: pi-hole
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etc-dnsmasq
  namespace: pi-hole
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  selector:
    matchLabels:
      app: pi-hole
  replicas: 1
  template:
    metadata:
      labels:
        app: pi-hole
    spec:
      serviceAccountName: pi-hole
      containers:
        - name: pi-hole
          image: pihole/pihole:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: etc-pihole
              mountPath: "/etc/pihole"
            - name: etc-dnsmasq
              mountPath: "/etc/dnsmasq.d"
          env:
            - name: TZ
              value: "Australia/Brisbane"
      volumes:
        - name: etc-pihole
          persistentVolumeClaim:
            claimName: etc-pihole
        - name: etc-dnsmasq
          persistentVolumeClaim:
            claimName: etc-dnsmasq
      nodeSelector:
        pi_level: level3
