---
apiVersion: v1
kind: Service
metadata:
  name: my-sql
  namespace: my-sql
spec:
  type: LoadBalancer
  ports:
    - port: 18888
      protocol: TCP
      targetPort: 3306
  selector:
    app: my-sql