---
apiVersion: v1
kind: Namespace
metadata:
  name: xteve
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xteve
  namespace: xteve
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xteve
  namespace: xteve
spec:
  selector:
    matchLabels:
      app: xteve
  replicas: 1
  template:
    metadata:
      labels:
        app: xteve
    spec:
      serviceAccountName: xteve
      containers:
        - name: xteve
          image: alturismo/xteve
          imagePullPolicy: Always