---
apiVersion: v1
kind: Service
metadata:
  name: xteve
  namespace: xteve
spec:
  type: LoadBalancer
  ports:
    - port: 34400
      protocol: TCP
      targetPort: 34400
  selector:
    app: xteve