apiVersion: v1
kind: Pod
metadata:
  name: secret2file
spec:
  containers:
    - name: demo
      image: arm64v8/busybox
      command: ["sleep"]
      args: ["1h"]
      # mount volume at a given path; secret to volume declared below:
      volumeMounts:
        - name: democredentialsvolume
          mountPath: /etc/democredentials
  volumes:
    # secret as volume
    - name: democredentialsvolume
      secret:
        secretName: democredentials