---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudctrl-cost-exporter
  labels:
    app-finops-cost-centre: CloudCtrlTeam
    app-team: CloudCtrl 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudctrl-cost-exporter
  namespace: cloudctrl-cost-exporter
spec:
  selector:
    matchLabels:
      app: cloudctrl-cost-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudctrl-cost-exporter
        app-finops-cost-centre: CloudCtrlTeam
        app-team: CloudCtrl 
    spec:
      containers:
        - name: cloudctrl-cost-exporter
          image: nginx
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cloudctrl-cost-exporter
  namespace: cloudctrl-cost-exporter
spec:
  type: ClusterIP
  ports:
    - port: 8888
      name: http
      protocol: TCP
      targetPort: 80
  selector:
    app: cloudctrl-cost-exporter