---
apiVersion: v1
kind: Namespace
metadata:
  name: jackett
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jackett
  namespace: jackett
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jackett-config
  namespace: jackett
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: jackett
spec:
  selector:
    matchLabels:
      app: jackett
  replicas: 1
  template:
    metadata:
      labels:
        app: jackett
    spec:
      serviceAccountName: jackett
      containers:
        - name: jackett
          image: lscr.io/linuxserver/jackett:arm64v8-latest
          imagePullPolicy: Always
          volumeMounts:
            - name: jackett-config
              mountPath: "/config"
          env:
            - name: TZ
              value: "Australia/Brisbane"
      volumes:
        - name: jackett-config
          persistentVolumeClaim:
            claimName: jackett-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: jackett
spec:
  selector:
    matchLabels:
      app: flaresolverr
  replicas: 1
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      serviceAccountName: jackett
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: jackett
spec:
  type: LoadBalancer
  ports:
    - port: 9117
      protocol: TCP
      targetPort: 9117
  selector:
    app: jackett
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: jackett
spec:
  type: LoadBalancer
  ports:
    - port: 8191
      protocol: TCP
      targetPort: 8191
  selector:
    app: flaresolverr
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jacket-ingress
  namespace: jackett
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/jackett`)
    kind: Rule
    services:
    - name: jackett
      port: 9117
      kind: Service
      namespace: jackett