---
apiVersion: v1
kind: Namespace
metadata:
  name: teamcity-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teamcity-agent
  namespace: teamcity-agent
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: teamcity-agent
  namespace: teamcity-agent
rules:
  # Allow TC server to launch agent pods via deployments
  - apiGroups: [""]
    resources: [ "pods" ]
    verbs: [ "get", "create", "list", "watch", "delete" ]
  - apiGroups: [""]
    resources: [ "deployments" ]
    verbs: [ "get", "list" ]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: teamcity-agent
rules:
  # Allow TC server to list namespaces to provide suggestions on the UI
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: teamcity-agent
  namespace: teamcity-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: teamcity-agent
subjects:
  - kind: ServiceAccount
    name: teamcity-agent
    namespace: teamcity-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: teamcity-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: teamcity-agent
subjects:
  - kind: ServiceAccount
    name: teamcity-agent
    namespace: teamcity-agent