---
apiVersion: v1
kind: Service
metadata:
  name: teamcity-server
  namespace: teamcity-server
spec:
  type: LoadBalancer
  ports:
    - port: 8111
      protocol: TCP
      targetPort: 8111
  selector:
    app: teamcity-server